### ISSUE TITLE
引入这个agent后项目日志不输出了 -- Slf4j can not log after adding  this agent

### ISSUE THREAD

**Issue by gabrielsky** [libinglong/skywalking-threadpool-agent#2]
```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>${slf4j.api.version}</version>
</dependency>
```
看了下代码原因应该是该项目引入了上面的包，agent的日志应该是要独立的把，这个只是接口，没有引入实现包，没有任何其他的日志配置，skywalking的日志是独立的，应该参考skywalking的做法

**Comment by libinglong** [comment]
slf4j会自动寻找实现类，如果没有实现类，不打印日志是正常情况。
按您说的情况，原本可以打印日志的项目，引入这个agent后却不打印日志，这很奇怪，需要进一步的分析，是否能提供更详细的信息？
Slf4j will auto find the StaticLoggerBinder in the classpath. It's normal not to print logs If there is no StaticLoggerBinder.
According to the situation you said, it is strange that the project that could print the log does not print the log after the introduction of this agent. It needs further analysis. Can you provide more detailed information?
> ```
> <dependency>
>     <groupId>org.slf4j</groupId>
>     <artifactId>slf4j-api</artifactId>
>     <version>${slf4j.api.version}</version>
> </dependency>
> ```
> 
> 看了下代码原因应该是该项目引入了上面的包，agent的日志应该是要独立的把，这个只是接口，没有引入实现包，没有任何其他的日志配置，skywalking的日志是独立的，应该参考skywalking的做法

**Comment by gabrielsky** [comment]
我使用https://start.spring.io/创建个java8的demo项目也会如此，和项目无关呢

主要代码：
```
@SpringBootApplication
@EnableScheduling
public class DemoApplication {

    private Logger logger = LoggerFactory.getLogger(DemoApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Scheduled(fixedRate = 1000L)
    public void test() {
        logger.info("hello , now:{}", LocalDateTime.now());
    }

}

```

pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

```

启动参数：
```
-javaagent:/data/apache-skywalking-apm-bin-es7/agent/skywalking-agent.jar
-javaagent:/data/apache-skywalking-apm-bin-es7/agent/skywalking-tool-agent-v1.0.0.jar
-Dskywalking.collector.backend_service=127.0.0.1:11800
```

只要javaagent增加了skywalking-tool-agent-v1.0.0.jar 启动的时候会如下错误
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by libinglong** [comment]
使用上述代码，没有复现问题。
上述代码中的依赖是包含logback的，正常来说，不应该找不到StaticLoggerBinder这个类。

Using the above code, there is no recurrence problem.
The dependency in the above code includes logback. Normally, the StaticLoggerBinder class should not be found

**Comment by gabrielsky** [comment]
> 使用上述代码，没有复现问题。
> 上述代码中的依赖是包含logback的，正常来说，不应该找不到StaticLoggerBinder这个类。

你是用java -jar启动测试的吗？

**Comment by libinglong** [comment]
> > 使用上述代码，没有复现问题。
> > 上述代码中的依赖是包含logback的，正常来说，不应该找不到StaticLoggerBinder这个类。
> 
> 你是用java -jar启动测试的吗？

你是正确的，使用java -jar确实会有问题，这是因为springboot使用特殊的类加载器以支持嵌套jar，而agent不使用该类加载器，因此找不到slf4j的实现类，可以参考skywalking的做法，不过由于这个项目很小，还是暂时先打到stdout

You are correct. There are indeed problems with using java -jar. This is because springboot uses a special class loader to support nested jars, and the agent does not use this class loader, so the implementation class of slf4j cannot be found. this project is very small, we just print to stdout instead of log like skywalking.

**Comment by libinglong** [comment]
v1.0.1版本修复了此问题
The release v1.0.1 has fixed this issue.
